---
- hosts: all
  tasks:
    - name: uninstall apache2
      apt: pkg=apache2 state=absent
      become: true
    - name: add apache2 apt repository
      apt_repository: repo=ppa:ondrej/apache2 update_cache=yes
      become: true
    - name: install latest apache2
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2
        - libapache2-mod-php5
      become: true
