---
- hosts: all
  tasks:
    - name: install MySQLdb
      apt: pkg=python-mysqldb state=latest
      become: true
    - name: install tasksel
      apt: pkg=tasksel state=latest
      become: true
    - name: install lamp
      shell: apt-get install lamp-server^
      become: true
