---
- hosts: all
  tasks:
    - name: install node
      apt: pkg={{ item }} state=latest
      become: true
      with_items:
        - nodejs
        - phantomjs
        - npm
    - name: install js tools
      npm: name={{ item }} global=yes
      become: true
      with_items:
        - grunt-cli
        - bower
        # - yo
        - coffee-script
